
title: Xin Fu


#sidebar links
email: xinfu AT bjtu DOT edu DOT cn
#phone: 012 345 6789
website_csdn: CSDN #do not add http://
website_zhihu: ZHIHU #do not add http://
#linkedin: alandoe
github: xinfu607
port: 4001
#Update all the sections by editing the files inside _includes folder.
